[tool.poetry]
name = "chanjo2"
version = "1.0.0"
description = "Next generation coverage analysis"
authors = ["moonso <mans.magnusson@scilifelab.se>"]

[tool.poetry_bumpversion.file."src/chanjo2/__init__.py"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.68.1"
sqlmodel = "^0.0.4"
python-multipart = "^0.0.5"
mysqlclient = "^2.1.0"
gunicorn = "^20.1.0"
requests = "^2.28.2"
pytest-cov = "^4.0.0"
validators = "^0.20.0"
pytest-mock = "^3.10.0"
uvicorn = "^0.21.1"
schug = "^1.2"
pyd4 = "^0.3.6.2"
python-dotenv = "^1.0.0"
mkdocs = "^1.4.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[tool.poetry.extras]
m1 = ["pyd4"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
